### ISSUE TITLE
Would a telegram bot connection out of the scope of this project?

### ISSUE THREAD

**Issue by Poolitzer** [Watchful1/UpdateMeBot#106]
Hey there.

I just discovered your bot, I love it. Just thought about adding a telegram connection, but before I dive into it (which will probably take up some time), I figured that asking you first if you think its over the line might be a good idea :)

Why Telegram? It is a messaging service with bot connection, so their notifications service may better. I had some trouble with reddits one, but maybe thats only me.

But you can also add the bot to a group/channel, so if a group of people on Telegram wants to receive updates from a thread and then discuss it in their group, they can do this easier with the bot.

I am not saying that the majority of the current users of your bot will end up using it in Telegram, but maybe some.

What do you think?

**Comment by Watchful1** [comment]
That might be something I could do long term, I am planning to implement support for reddit's built in chat once they release their API for it. But it's going to take some major re-architecting, so I don't think I would accept a pull request for it.

You would probably be able to use ifttt.com to send a telegram message when you get a notification message from the bot.

**Comment by Poolitzer** [comment]
Hmm, thanks for the hint
